name: Cleanup All Actions History

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Delete workflow runs in batches
      run: |
        while true; do
          run_ids=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/actions/runs | jq -r '.workflow_runs[].id' | head -n 20)

          if [ -z "$run_ids" ]; then
            echo "No more runs to delete."
            break
          fi

          for run_id in $run_ids; do
            if [ "$run_id" == "${{ github.run_id }}" ]; then
              echo "Skipping current workflow run $run_id"
              continue
            fi
            echo "Deleting workflow run $run_id"
            response=$(curl -s -o /dev/null -w "%{http_code}" -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id)
            if [ "$response" == "403" ]; then
              echo "Could not delete the workflow run $run_id due to permission issues."
              continue
            fi
          done

          remaining_runs=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/actions/runs | jq '.total_count')
          if [ "$remaining_runs" == "1" ]; then
            echo "Only the current workflow run is left. Exiting."
            break
          fi
          echo "There are still $remaining_runs runs left."
        done
