name: Trigger Nightly Workflows

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  trigger_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger bookworm-xfce-standard-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/minios-linux/minios-nightly/actions/workflows/bookworm-xfce-standard-amd64.yml/dispatches \
          -d '{"ref":"master"}'

      - name: Trigger bookworm-xfce-standard-i386
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/minios-linux/minios-nightly/actions/workflows/bookworm-xfce-standard-i386.yml/dispatches \
          -d '{"ref":"master"}'

      - name: Trigger bookworm-xfce-toolbox-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/minios-linux/minios-nightly/actions/workflows/bookworm-xfce-toolbox-amd64.yml/dispatches \
          -d '{"ref":"master"}'

      - name: Trigger bookworm-flux-minimum-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/minios-linux/minios-nightly/actions/workflows/bookworm-flux-minimum-amd64.yml/dispatches \
          -d '{"ref":"master"}'

      - name: Trigger bookworm-flux-minimum-i386
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/minios-linux/minios-nightly/actions/workflows/bookworm-flux-minimum-i386.yml/dispatches \
          -d '{"ref":"master"}'

      - name: Trigger buster-xfce-standard-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/minios-linux/minios-nightly/actions/workflows/buster-xfce-standard-amd64.yml/dispatches \
          -d '{"ref":"master"}'

      - name: Trigger buster-xfce-standard-i386
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/minios-linux/minios-nightly/actions/workflows/buster-xfce-standard-i386.yml/dispatches \
          -d '{"ref":"master"}'

      - name: Trigger bookworm-xfce-puzzle-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/minios-linux/minios-nightly/actions/workflows/bookworm-xfce-puzzle-amd64.yml/dispatches \
          -d '{"ref":"master"}'

      - name: Trigger bookworm-xfce-ultra-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/minios-linux/minios-nightly/actions/workflows/bookworm-xfce-ultra-amd64.yml/dispatches \
          -d '{"ref":"master"}'

      - name: Trigger bookworm-lxqt-standard-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/minios-linux/minios-nightly/actions/workflows/bookworm-lxqt-standard-amd64.yml/dispatches \
          -d '{"ref":"master"}'

      - name: Trigger sid-xfce-standard-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/minios-linux/minios-nightly/actions/workflows/sid-xfce-standard-amd64.yml/dispatches \
          -d '{"ref":"master"}'

      - name: Trigger sid-xfce-standard-i386
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/minios-linux/minios-nightly/actions/workflows/sid-xfce-standard-i386.yml/dispatches \
          -d '{"ref":"master"}'
